### ISSUE TITLE
Mobile layout "breaks" when on-screen keyboard is visible

### ISSUE THREAD

**Issue by biwecka** [pinshelf/pinshelf.github.io#43]
Video showing the current behavior:
https://github.com/pinshelf/pinshelf.github.io/assets/26962093/5efdaffc-28a2-449f-95d5-6e6ab9a48800

Possible solutions:
- using the dynamic view port height for the whole page layout

Related to #22

**Comment by KTDevelopment** [comment]
Sieht nach einem Safari Bug / Problem aus.
Auf Chrome (Android) tritt der Fehler nicht auf. 
Wenn man die App als PWA öffnet besteht dieses Problem ebenfalls nicht.
Da dieses Problem nur im mobile Safari auftritt und daher der Aufwand den Nutzen aktuell nicht aufwiegt, wird der Issue geschlossen.
