### ISSUE TITLE
Status bar color does not match the application

### ISSUE THREAD

**Issue by biwecka** [pinshelf/pinshelf.github.io#49]
Light mode:
![IMG_9061](https://github.com/pinshelf/pinshelf.github.io/assets/26962093/74382924-43ac-428d-877a-7d91a83696ab)

Dark mode:
![IMG_9062](https://github.com/pinshelf/pinshelf.github.io/assets/26962093/142315a5-640c-4dcb-80da-4ca7afbb85dd)

**Comment by KTDevelopment** [comment]
mann kann wohl mit 

`<meta name="theme-color" content="#014473">` die Farbe bei Firefox, Chrome und Opera setzen

und mit der Kombination aus:

```
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
```

die Werte für iOS.
für "apple-mobile-web-app-status-bar-style" gibt es drei werte: default, black, black-translucent 


siehe: https://codeburst.io/progressive-web-apps-customize-status-bar-23c4b2de590f

vielleicht kann man damit was erreichen, wobei es sich bei meinem iOS Simulator ok verhält, nur wenn ich aktiv etwas anderes als den System default auswähle passen die Farben nicht zusammen.

**Comment by biwecka** [comment]
`<meta name="apple-mobile-web-app-capable" content="yes">` habe ich mal gesetzt, weil das in der Apple Doku auch drin steht.
Den anderen Wert habe ich ausprobiert und dabei wird die Status Bar dann wirklich durchsichtig. Das heißt wenn man scrollt und Overflow nach oben hat, wir der Overflow/Content über unserer Toolbar wieder sichtbar. Um das zu verhindern habe ich mit dem Tag `<meta name="theme-color" ...>` feste Farben gesetzt.

**Comment by biwecka** [comment]
Closed by
- #55
